### ISSUE TITLE
Distance incorrect

### ISSUE THREAD

**Issue by davidak** [Alovoa/alovoa#121] opened 2021-11-29 20:56 UTC
I created a second account for testing and both of my accounts are at the same location (i can't even change it), but the distance shown is 215 km!

With such behavior, the app is not useful.

**Comment by davidak** [comment] 2021-11-30 14:03
Today i switched my profile to "I want to meet new people" and see 4 people in the search. All say 0km, but one is from CA and i'm still in germany. So this is also wrong.

**Comment by Nonononoki** [comment] 2021-12-04 16:31
I have noticed the 0km bug, but I cannot reproduce the first one where the shown distance greatly differs. 
Are you sure both accounts have the same (or almost same) location? If a location has been already set it will be used for consecutive searches unless changed in the search page (cog button).

**Comment by davidak** [comment] 2021-12-04 18:14
>Are you sure both accounts have the same (or almost same) location?

No. I don't see my location and have no way to set it.

>unless changed in the search page (cog button)

when i click the cog symbol button on the top right on https://alovoa.com/search i get this dialog. no option to change the location or see it

![Screenshot from 2021-12-04 19 12 44](https://user-images.githubusercontent.com/91113/144720128-cf350ff2-7d8e-4953-b23f-4ff1b2058dc2.png)

**Comment by Nonononoki** [comment] 2021-12-04 18:44
The location is not shown because the average user does not need to see it. If the permission is set the location will be fetched from the Geolocation API of the browser. Otherwise the user can pick a location from the map. Location will be set when the search button is clicked.

**Comment by davidak** [comment] 2021-12-04 19:03
Then i can't help you debugging this issue.

**Comment by mruncreative** [comment] 2022-03-13 20:05
Can confirm. Shows people from all over the world with 0km. I picked the correct location on the map.

**Comment by mruncreative** [comment] 2022-03-13 20:12
I just liked a 0km user. It said an error occured.

**Comment by mruncreative** [comment] 2022-03-13 20:14
It says 409 in the console.

**Comment by Nonononoki** [comment] 2022-03-16 07:28
Should now be fixed with this commit: e122886b8ce781f8bd9da545a69e601473937002
Existing users must update their location once

**Closed by Nonononoki** 2022-03-16 07:28 UTC
